### ISSUE TITLE
PG::ConnectionBad

### ISSUE THREAD

**Issue by JayRebuilds** [CanciuCostin/android-spyware#46]
<html>
<body>
<h2 style="color: rgb(197, 47, 36); line-height: 25px; font-family: helvetica, verdana, arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(250, 250, 250); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">fe_sendauth: no password supplied</h2><div class="source " id="frame-source-0-0" style="border: 1px solid rgb(217, 217, 217); background: rgb(236, 236, 236); width: 978px; color: rgb(51, 51, 51); font-family: helvetica, verdana, arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="info" style="margin: 0px; padding: 0.5em;">Extracted source (around line<span> </span><strong style="margin: 0px; padding: 0px;">#58</strong>):</div><div class="data" style="margin: 0px; padding: 0px; font-size: 10.4px; overflow: auto; background-color: rgb(255, 255, 255);">

56 57 58 59 60 61 | ### Convenience alias for PG::Connection.new. 	def self::connect( *args ) 		return PG::Connection.new( *args ) 	end
-- | --

</div></div><p style="font-family: helvetica, verdana, arial, sans-serif; font-size: 13px; line-height: 18px; color: rgb(51, 51, 51); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(250, 250, 250); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><code>Rails.root: C:/Windows/system32/android-spyware</code></p><div id="traces-0" style="color: rgb(51, 51, 51); font-family: helvetica, verdana, arial, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(250, 250, 250); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a href="http://127.0.0.1:3000/#" onclick="hide('Framework-Trace-0');hide('Full-Trace-0');show('Application-Trace-0');; return false;" style="color: rgb(152, 9, 5);">Application Trace</a><span> </span>|<span> </span><a href="http://127.0.0.1:3000/#" onclick="hide('Application-Trace-0');hide('Full-Trace-0');show('Framework-Trace-0');; return false;" style="color: rgb(152, 9, 5);">Framework Trace</a><span> </span>|<span> </span><a href="http://127.0.0.1:3000/#" onclick="hide('Application-Trace-0');hide('Framework-Trace-0');show('Full-Trace-0');; return false;" style="color: rgb(152, 9, 5);">Full Trace</a><div id="Full-Trace-0" style="display: block;"><code style="font-size: 11px;"><a class="trace-frames trace-frames-0" data-exception-object-id="93444840" data-frame-id="0" href="http://127.0.0.1:3000/#" style="color: rgb(102, 102, 102);">pg-1.2.2-x64 (mingw32) lib/pg.rb:58:in `initialize'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="93444840" data-frame-id="1" href="http://127.0.0.1:3000/#" style="color: rgb(102, 102, 102);">pg-1.2.2-x64 (mingw32) lib/pg.rb:58:in `new'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="93444840" data-frame-id="2" href="http://127.0.0.1:3000/#" style="color: rgb(102, 102, 102);">pg-1.2.2-x64 (mingw32) lib/pg.rb:58:in `connect'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="93444840" data-frame-id="3" href="http://127.0.0.1:3000/#" style="color: rgb(197, 47, 36);">activerecord (6.0.2.1) lib/active_record/connection_adapters/postgresql_adapter.rb:46:in `postgresql_connection'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="93444840" data-frame-id="4" href="http://127.0.0.1:3000/#" style="color: rgb(102, 102, 102);">activerecord (6.0.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:889:in `new_connection'</a><br><a class="trace-frames trace-frames-0" data-exception-object-id="93444840" data-frame-id="5" href="http://127.0.0.1:3000/#" style="color: rgb(102, 102, 102);">activerecord (6.0.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:933:in `checkout_new_connection'</a></code></div></div>
</body>
</html>

**Comment by CanciuCostin** [comment]
Is this error thrown on Docker deployment? Or after build?
What is the OS?

**Comment by JayRebuilds** [comment]
after build,

**Comment by JayRebuilds** [comment]
ADB connection to be exact

**Comment by CanciuCostin** [comment]
Seems that you are not connected to the postgresdb. Not sure if you've configured a local instance or not.

You can try to run the postgres and msf instances from docker and keep your rails instance locally for build.
Try to set these environment variables:
```
ANDROIDSPYWARE_DATABASE_HOST=localhost
ADB_HOST=localhost
RAILS_HOST=127.0.0.1
```
and run docker-compose up after commenting the rails service
```
version: "3.7"
services:
#  rails-app:
#    image: costincanciu/android-spyware:latest
#    depends_on:
#      - db
#      - metasploit
#    ports:
#      - "80:80"
#    volumes:
#      - ./files:/app/android-spyware/files
#      - //var/run/docker.sock://var/run/docker.sock
#    entrypoint: sh -c "mkdir -p /app/android-spyware/files/payloads /app/android-spyware/files/dumps/calllogs_dumps /app/android-spyware/files/dumps/contacts_dumps /app/android-spyware/files/dumps/microphone_recs /app/android-spyware/files/dumps/pictures /app/android-spyware/files/dumps/screen_snaps /app/android-spyware/files/dumps/sms_messages_dumps /app/android-spyware/files/dumps/whatsapp | rails s -b 0.0.0.0 -p 80"
#    tty: true
#    environment:
#      ADB_HOST: gateway.docker.internal
#      #MAPS_API_KEY: YOUR KEY HERE
  db:
    image: costincanciu/android-spyware-db:latest
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  metasploit:
    container_name: kali_container
    image: costincanciu/android-spyware-msf:latest
    ports:
    - "2222:2222"
    - "3333:3333"
    - "4444:4444"
    user: root
volumes:
  db:
```
